import type { Knex } from 'knex';
import { cleanupCache } from './hls-transcoder';

// The default file for an entry is the alphabetically-first filename.
export async function pickDefaultFile(dbOrTrx: Knex, videoId: string): Promise<any> {
  return dbOrTrx('video_files')
    .where('video_id', videoId)
    .orderBy('filename', 'asc')
    .first();
}

// Mark `file` as the entry's default: flip the is_default flags and mirror its per-file columns
// onto the videos row (the denormalized copy read by list/search/display surfaces).
export async function setDefaultFile(dbOrTrx: Knex, videoId: string, file: any): Promise<void> {
  await dbOrTrx('video_files').where('video_id', videoId).update({ is_default: 0 });
  await dbOrTrx('video_files').where('id', file.id).update({ is_default: 1 });
  await dbOrTrx('videos').where('id', videoId).update({
    default_file_id: file.id,
    filename: file.filename,
    full_path: file.full_path,
    length: file.length,
    width: file.width,
    height: file.height,
    video_codec: file.video_codec,
    audio_codec: file.audio_codec,
    bitrate: file.bitrate,
    framerate: file.framerate,
    file_size: file.file_size,
    updated_at: new Date().toISOString(),
  });
}

// The surviving entry when merging a same-code group: prefer matched, then oldest, then smallest id.
function pickSurvivor(rows: any[]): any {
  const sorted = [...rows].sort((a, b) => {
    const am = a.matched ? 1 : 0;
    const bm = b.matched ? 1 : 0;
    if (am !== bm) return bm - am;
    const ac = a.created_at || '';
    const bc = b.created_at || '';
    if (ac !== bc) return ac < bc ? -1 : 1;
    return a.id < b.id ? -1 : a.id > b.id ? 1 : 0;
  });
  return sorted[0];
}

// Merge a group of videos rows that share the same code into a single entry. The losing rows'
// files and relations are re-parented onto the survivor, then the losing rows are deleted.
export async function mergeGroup(db: Knex, rows: any[]): Promise<{ survivorId: string; losers: string[] }> {
  const survivor = pickSurvivor(rows);
  const survivorId = survivor.id;
  const loserIds = rows.filter((r) => r.id !== survivorId).map((r) => r.id);
  if (loserIds.length === 0) return { survivorId, losers: [] };

  await db.transaction(async (trx) => {
    // Re-parent physical files onto the survivor (default recomputed below).
    await trx('video_files').whereIn('video_id', loserIds).update({ video_id: survivorId, is_default: 0 });

    // Re-parent genres (composite PK — conflict-safe upsert, then drop loser rows).
    const loserGenres = await trx('video_genres').whereIn('video_id', loserIds).select('genre_id');
    for (const g of loserGenres) {
      await trx('video_genres').insert({ video_id: survivorId, genre_id: g.genre_id }).onConflict(['video_id', 'genre_id']).ignore();
    }
    await trx('video_genres').whereIn('video_id', loserIds).del();

    // Re-parent cast.
    const loserCast = await trx('video_cast').whereIn('video_id', loserIds).select('cast_id');
    for (const c of loserCast) {
      await trx('video_cast').insert({ video_id: survivorId, cast_id: c.cast_id }).onConflict(['video_id', 'cast_id']).ignore();
    }
    await trx('video_cast').whereIn('video_id', loserIds).del();

    // Re-parent field sources — the survivor's own sources win (its manual edits are never clobbered).
    const loserSources = await trx('field_sources').whereIn('video_id', loserIds).select('field', 'source');
    for (const s of loserSources) {
      await trx('field_sources').insert({ video_id: survivorId, field: s.field, source: s.source }).onConflict(['video_id', 'field']).ignore();
    }
    await trx('field_sources').whereIn('video_id', loserIds).del();

    // playback_state has a video_id PK, so only one resume position survives. Keep the survivor's;
    // if it has none, adopt the loser's most-recently-viewed one.
    const survivorPlayback = await trx('playback_state').where('video_id', survivorId).first();
    if (!survivorPlayback) {
      const loserPlayback = await trx('playback_state')
        .whereIn('video_id', loserIds)
        .orderBy('last_viewed', 'desc')
        .first();
      if (loserPlayback) {
        await trx('playback_state').where('video_id', loserPlayback.video_id).update({ video_id: survivorId });
      }
    }
    await trx('playback_state').whereIn('video_id', loserIds).del();

    // coverage_results has no FK; drop loser rows (they are regenerated by coverage runs).
    await trx('coverage_results').whereIn('video_id', loserIds).del();

    // Delete the losing entries (cascades any remaining children; their files are already re-parented).
    await trx('videos').whereIn('id', loserIds).del();

    // Recompute the default file across the survivor's now-combined file set and mirror it onto videos.
    const def = await pickDefaultFile(trx, survivorId);
    if (def) await setDefaultFile(trx, survivorId, def);
  });

  return { survivorId, losers: loserIds };
}

// Find every non-empty code shared by 2+ entries and merge each group into one. Cleans up the
// orphaned HLS caches of the deleted entries. Shared by the merge worker and the scrape worker.
export async function mergeAllDuplicates(
  db: Knex,
  onProgress?: (update: any) => void,
): Promise<{ mergedGroups: number; removedRows: number }> {
  const groups = await db('videos')
    .whereNotNull('code').where('code', '!=', '')
    .select('code').count('* as n').groupBy('code').having(db.raw('count(*) >= 2'));

  let mergedGroups = 0;
  let removedRows = 0;
  let processed = 0;
  if (onProgress) onProgress({ total: groups.length });

  for (const g of groups) {
    if (onProgress) onProgress({ currentFile: String(g.code), step: 'Merging' });
    const rows = await db('videos').where('code', g.code).orderBy('created_at', 'asc').orderBy('id', 'asc');
    if (rows.length >= 2) {
      try {
        const { losers } = await mergeGroup(db, rows);
        if (losers.length > 0) {
          mergedGroups++;
          removedRows += losers.length;
          // HLS caches are keyed by videoId, so the deleted losers' must be cleared. Thumbnails are
          // keyed by code (which the survivor and losers of a merge share), so they are left untouched.
          for (const id of losers) cleanupCache(id);
        }
      } catch (err: any) {
        console.error(`[merge] code=${g.code} FAILED:`, err.message);
      }
    }
    processed++;
    if (onProgress) onProgress({ processed, added: mergedGroups, removed: removedRows });
  }

  return { mergedGroups, removedRows };
}
